<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="Harmanjeet" failures="1" tests="7" name="Capstone.Login_Home_Page" time="10.796" errors="0" timestamp="4 Jun 2021 02:25:54 GMT">
  <testcase classname="Capstone.Login_Home_Page" name="Login" time="10.241"/>
  <testcase classname="Capstone.Login_Home_Page" name="HomePageVerifyTitle" time="0.025"/>
  <testcase classname="Capstone.Login_Home_Page" name="HomePageVerifyLogo" time="0.101"/>
  <testcase classname="Capstone.Login_Home_Page" name="HomePageDropDownsCount" time="0.036"/>
  <testcase classname="Capstone.Login_Home_Page" name="HomePageDropDownsName" time="0.202"/>
  <testcase classname="Capstone.Login_Home_Page" name="VerifyVisitTagHomePagePresence" time="0.077"/>
  <testcase classname="Capstone.Login_Home_Page" name="VerifyVisitTagHomePageName" time="0.079">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;null&amp;gt; but was:&amp;lt;Visit&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<null> but was:<Visit>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:480)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at Capstone.Login_Home_Page.VerifyVisitTagHomePageName(Login_Home_Page.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase>
</testsuite>
